version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: techfx-postgres
    restart: always
    environment:
      POSTGRES_DB: techfx
      POSTGRES_USER: techfx_user
      POSTGRES_PASSWORD: techfx_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
